spring:
  application:
    name: eurekaClient

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/,http://localhost:8763/eureka/
  server:
    enable-self-preservation: false

server:
  port: 8760
  
env:
  dev
  
lable:
  release
