spring:
  application:
    name: eurekaClient
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false
  instance:
      # 心跳间隔时间
      lease-renewal-interval-in-seconds: 2
      # 最后一次心跳时间后leaseExpirationDurationInSeconds秒就认为是下线了
      lease-expiration-duration-in-seconds: 6

server:
  port: 9101
  
env:
  test3
  
lable:
  release
